### ISSUE TITLE
Add TypeScript usage to docs

### ISSUE THREAD

**Issue by ai** [lukeed/uvu#121]
Hi. Amazing project. I want to try it for my open source, but do not know how to use it with tests on TypeScript (to test `.d.ts` files of my projects).

Maybe I am not the only user with this question. Adding TypeScript to docs could be useful.

**Comment by lukeed** [comment]
Hey, thanks! :)

Could [this example](https://github.com/lukeed/uvu/tree/master/examples/typescript) help? 

You can also check out my `worktop` project which is purely in TS. That example is also slightly more complicated because it has multiple self-referential imports & so it also brings in `module-alias` to rectify that part... nothing to do with TS though. Also, worktop is using a custom esbuild loader for running the TS source and tests, which i mention just to point out that you can use esbuild, ts-node, esbuild-register, babel, ...etc -- all via a `uvu --require <thing>` hook

**Comment by ai** [comment]
Exactly what I want.

For other users, we can add links from `README.md`

**Comment by lukeed** [comment]
There's a link to all examples [at the top of Usage](https://github.com/lukeed/uvu#usage) which is near the top of the readme. I would have thought that was enough, since that's also how the actual documentation is linked out too?

**Comment by ai** [comment]
My user scenario was (and I assume that it is popular scenario):

1. Worry about TypeScript support
2. Search for `typescript` in README.md
3. See `0 results` and decide that there is no support

**Comment by lukeed** [comment]
Gotcha, fair enough :)

I'll put together a docs page and link to it somewhere from the readme
