### ISSUE TITLE
uvu with svelte

### ISSUE THREAD

**Issue by jerrythomas** [lukeed/uvu#122]
Uvu makes it painless to test ESM modules without the -r esm.
However, the svelte example still suggests using `-r esm and -r tests/setup/register.js`. 

Whe I try to use it I get the error below
```text
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module
require() of ES modules is not supported.
```
Is there a way that svelte testing can be done without the `require`?

**Comment by lukeed** [comment]
Thanks

> Is there a way that svelte testing can be done without the require?

No because the `*.svelte` files need a --require hook in order to be compiled. And any use of --require automatically moves uvu into CJS mode.

The ESM --loader hook API is still experimental, but exists. I don't recommend experimental APIs so there's no example of it, but you're welcome to try & piece it together yourself :) Circle back with a TLDR if you decide to go this route.

Hope that helps a bit

**Comment by brev** [comment]
Hi @jerrythomas @lukeed,

I've done some starter work on using ESM loader hooks for this: https://github.com/brev/esm-loader-svelte

My ESM-only testing of SvelteKit with UVU is now working decently. Svelte component imports are compiled. CSS/PostCSS style imports are no-op instead of failing. JSON imports can be done with another experimental node flag.

**Comment by brev** [comment]
Just updated npm to a new version, it now also does preprocessing.
