### ISSUE TITLE
Specify a glob pattern

### ISSUE THREAD

**Issue by ryands17** [lukeed/uvu#13]
Is there any way to specify a glob instead of a folder that only files ending in `spec` or `test` are considered?

**Comment by lukeed** [comment]
Hey, this is the matching logic: https://github.com/lukeed/uvu/blob/master/src/parse.js#L15

What this means is that if you pass a `dir` then all files inside are read. If you pass a `pattern` (positional) it'll be converted to a RegExp and used to match your tests. This means you can pass _anything_ as a `pattern` so long as it passes through `new RegExp` for an expected output.

Here's an example of that: https://github.com/lukeed/uvu/blob/master/examples/monorepo/package.json#L4

What's happening here is that the `packages` directory is being traversed, but only things that match `/tests/i` are considered tests. In this case, `tests` is the name of a subdirectory, but it could have been anything. For example,  something like `uvu packages "^foo.\\d+.js$"` is _effectively_ equivalent to `packages/**/foo.\d+.js` (I say "effectively" because I don't actually know offhand how to express the same file specificity within a globstar pattern -- uvu's is more explicit than this glob pattern). 

Then there are `-i/--ignore` flags that are cast to RegExp (exactly like `pattern`) and as the name suggests, they're used to ignore/discard files that would otherwise be picked up in traversal. I typically use this to ignore my `test/fixtures` directory and/or a `test/helpers.js` file, for example. Here's how [`sirv`](https://github.com/lukeed/sirv/blob/master/package.json#L11) uses it.

All in all, `uvu` purposefully doesn't follow the same glob-pattern argument that other test runners employ because:
1. You almost always want a generic directory match anyway
2. If you don't, you end up with a super complex matching pattern that (probably) took a while to get right on the first place
3. Glob pattern parsing/matching is actually a significant amount of code (and work) to execute on startup, especially when there's a super simple & (imo) more straightforward approach that gets you to the same spot

Hope that helps!

**Comment by gr2m** [comment]
For anyone (like my future self 🤣) who wants to multiple test files from different folders, this command will run all tests from

1. `./test.js`
2. `./examples/*/test.js`

```
uvu . '^(examples/.*/)?test.js$'
```

**Comment by kevinsimper** [comment]
And if you have a dist folder where you only want to match on .test.js files

```
npx uvu dist ".*\.test\.js"
```
