### ISSUE TITLE
Still can’t run TS and ESM

### ISSUE THREAD

**Issue by ai** [lukeed/uvu#144]
Thanks for https://github.com/lukeed/uvu/pull/143 changes.

But I still can’t run test. [Repo](https://github.com/ai/nanodelay/tree/uvu).

```sh
$ npx tsm node_modules/uvu/bin.js test **/*.test.ts
(node:19956) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

  Total:     0
  Passed:    0
  Skipped:   0
  Duration:  0.10ms
```

**Comment by lukeed** [comment]
I ran both options successfully inside the "typescript.module" example, looking at your repo for setup information.

The only thing different here is your use of npx, so I'd remove that and see if it still fails for you. Never actually ran uvu thru npx before, so maybe there's a weird interaction there.

**Comment by Kamrulhasan12345** [comment]
@lukeed I was able to do VSCode debugging with the tsm module example with VSCode debug auto attach mode

**Comment by maxmilton** [comment]
Is the issue now that the tests are not running? Did you perhaps forget to call `test.run()`?

**Comment by ai** [comment]
I forgoet to add `test.run()` 😅

But after adding it back I still have the same problem of 0 tests running.

**Comment by ViZhe** [comment]
@ai 
https://github.com/lukeed/uvu/blob/master/docs/cli.md#matching
`Unlike other test runners, uvu intentionally does not rely on glob patterns.`

so
`tsm node_modules/uvu/bin.js test index.test.ts`
or
`tsm node_modules/uvu/bin.js test \\.test\\.ts$`

will do job :)

<img width="438" alt="изображение" src="https://user-images.githubusercontent.com/8091902/139529304-3bdd224e-8c59-42c3-a702-917701fd2d01.png">

**Comment by ai** [comment]
Thanks. Fixed.

**Comment by lukeed** [comment]
Oh, haha, thank you @maxmilton and @ViZhe for helping! I was so focused on the paths to tsm & uvu bins that I didn't even notice the uvu arguments 😅

Glad you were able to get it sorted out @ai

**Comment by maxmilton** [comment]
Awesome it was fixed :)

I've forgotten to call run() before too so it's something that's on mind when using `uvu`. It was a bit strange at first since other test runners have magical abstraction, but I've come to really appreciate the explicit nature of uvu, especially because tests files are self-contained.

**Comment by ai** [comment]
Is it possible to add some warning to `uvu` runner on file without `run()` call?

I'm afraid that this error is too easy to make (in my case, I will be protected by test coverage, but other user will see warning very helpful).

**Comment by lukeed** [comment]
No, that's a core API requirement and just needs to be known. I don't want to add a bunch of analysation code for something necessary/critical for operation. You don't see a warning when forgetting a `.listen()` on Express/native http servers.

The next minor release will include #43 export, which will automatically call `.run()` so that users don't have to. It will help tackle the same problem but from a different direction :)
