### ISSUE TITLE
How i can require setup/register with type: module in package.json

### ISSUE THREAD

**Issue by Valexr** [lukeed/uvu#148]
```json
// package.json
{
  "type": "module",
  "scripts": {
    "test": "uvu -r esm tests -r setup/register"
}
```
error - `uvu.parser` loaded from index.js - not from index.mjs... ?🤔
```sh
Debugger attached.
/node_modules/.pnpm/uvu@0.5.2/node_modules/uvu/parse/index.js:1
Error [ERR_REQUIRE_ESM]: require() of ES Module /setup/register.js from /node_modules/.pnpm/uvu@0.5.2/node_modules/uvu/parse/index.js not supported.
Instead change the require of register.js in /node_modules/.pnpm/uvu@0.5.2/node_modules/uvu/parse/index.js to a dynamic import() which is available in all CommonJS modules.
```

but with `uvu -r tsm tests -r setup/register` import modules work fine 👍🏻 for `.test.(ts|js)` files 🤔

**Comment by lukeed** [comment]
You can't `-r setup/register` on its own if register.js is ESM or the entire project is type:module. Require hooks are for CommonJS so you will always get that error.

As you saw, you have to use something like `-r tsm` first which will allow you to mix n match ESM and CJS because tsm rewrites things on the fly. That's part of the reason why I made it :)
