### ISSUE TITLE
docs: how to test components that use static assets/css modules

### ISSUE THREAD

**Issue by Hotell** [lukeed/uvu#16]
Hi @lukeed , would you be able to add to examples how can folks write tests, for example React components, that use **css modules** or contain **static assets** (images....) ?

awesome work btw!

**Comment by lukeed** [comment]
Hey, thanks~!

I have a browser layer that's coming, which will make some of this easier (IMO) but in the meantime I can put together an example like this. The tricky part is that css-modules – or even including assets – is going to include a full bundler setup inside the example, which may be (a) overkill for a demonstration (b) obscure the demonstration itself since there's so much added noise.

What if the example just included rendering a component and asserting it was rendered correctly (thru snapshot?) and that it updates a counter on click, or something like that?

**Comment by lukeed** [comment]
Added separate examples that showed how to test Svelte and Preact components.

I did not include css-modules or static assets because those are custom to your source and don't actually change much. You'd still end up with a `container` item that you query against, and then assert something based on the test. The only difference is that with css-modules, you may not know what the destination classname is without re-running PostCSS or some other part of your build process...which I don't recommend.

Instead, I'd probably go with a `test-id=""` attribute on the things you want to query against, and then use [`babel-plugin-jsx-remove-data-test-id`](https://www.npmjs.com/package/babel-plugin-jsx-remove-data-test-id) to remove those for PROD builds – simply because you'd (probably) rather have legible test identifiers, than use CSS output gibberish.

**Comment by Hotell** [comment]
Can't agree more with what you said regarding testing.

Looks good. Thanks a lot!
