### ISSUE TITLE
Can uvu be configured to resolve alias paths?

### ISSUE THREAD

**Issue by kee-oth** [lukeed/uvu#161]
I have an alias defined for my project (a Vite project) that alias' `#` to my `src` directory. uvu can't resolve it since it doesn't know what's going on. Is there a way to configure path alias' in uvu?

Thanks!

**Comment by lukeed** [comment]
uvu directly wouldn't do this – this is typically what require hooks and/or esm loaders are for, since theyre affecting & hooking into the Node process's runtime behavior, not uvu's

uvu does a similar thing for its own tests: I use [`module-alias`](https://www.npmjs.com/package/module-alias) and define [some configuration](https://github.com/lukeed/uvu/blob/master/package.json#L76-L80)

When used _with_ uvu, your usage will probably look something like this:

```sh
$ uvu -r module-alias/register tests
```

with your `module-alias` configuration in place, of course

Hope that helps~!

**Comment by davidprae** [comment]
Awesome! This worked perfectly, thanks!
