### ISSUE TITLE
docs: how to run tests in watch mode

### ISSUE THREAD

**Issue by Hotell** [lukeed/uvu#17]
How to run tests in watch mode? I assume `nodemon` or [watch](https://github.com/mikeal/watch) is the answer ? Would love to see it included in examples as well.

cheers!

**Comment by lukeed** [comment]
Right now I'd use something like [`watchexec`](https://github.com/watchexec/watchexec) – which would look like this:

```sh
$ watchexec -w src -w tests npm test
```

This (recursively) watches all files within the `src` and `tests` directories, rerunning `npm test` whenever there's a change.

Although I might make my own watch CLI, which would look something like:

```sh
$ watch src tests -- npm test
```

It was suggested that `uvu --watch` exists, which I can't say i'm 100% against, however, my hesitation with that (and it applies to my own watch CLI too) is that I still have to either (a) include all of `chokidar`; or (b) become familiar with the bugs/edge cases that `chokidar` solves & apply them to my own solution; (c) just rely on native `fs.FSWatcher` and hope for the best.

The benefit of a separate watch CLI is that those solutions/problems are contained to _that_ module. If `uvu --watch` exists and proves to be buggy, then  ***everyone*** inherits that code and it becomes a problem or it becomes big & burly. And there will be users (myself included) that never reach for that feature and it's just _there_ taking up space.

Sorry I'm ranting now – but to wrap up: I think all-in-one solutions _can_ sometimes be nice, but especially in the JS community, I think we forget that CLIs are meant to be piped into and chained together. A CLI should do one thing well and be flexible enough to work with other CLIs – or at least self-contained so that it doesn't matter how it gets invoked. Because of this, I'm definitely leaning towards a separate watch CLI, although I do understand the appeal of a `uvu` builtin.

---

> Related: There was a little [Twitter thread](https://twitter.com/m0t0r_/status/1281336275476402177) about this

**Comment by lukeed** [comment]
Ok. I have created  [`watchlist`](https://github.com/lukeed/watchlist), which is my first pass as a watcher cli.
I will need some feedback to bring this to 1.0 – I know there are inconsistencies with Windows right now, but it's late for me and I don't currently have access to a Windows machine.

The `watchlist` usage is exactly as described above:

```sh
$ watchlist src tests -- npm test
```

The `--` is important – it's what separates `watchlist` from the command you want to run. 
It's also what makes it possible to pass option flags to your command (`uvu` in this case):

```sh
$ watchlist src tests -- uvu tests -r esm -i fixtures
```

I will add a `/docs` item tomorrow for this.

**Comment by Hotell** [comment]
> Sorry I'm ranting now

Haha no worries, I see where are you coming from and I can definitely relate 👍

Regarding simple CLIs and stuff again, I can't agree more, and yup I'm favor to have watcher as separate package.

TY!

**Comment by aleclarson** [comment]
**Idea:** An `uvu-watch` package could be auto-installed when the `--watch` flag is used for the first time.

@lukeed If you decide to pursue this idea, give [filespy](https://github.com/alloc/filespy) a try. :)

**Comment by lukeed** [comment]
Thank you, but I'm really not a fan of runtime-installations, especially by other dependencies. I'd always much rather _you know_ what you're using **and why** – otherwise it feels like a dirty surprise IMO.

Nothing else will be added in relation to this ticket, since everyone I've talked to has found success with `watchlist` and/or `watchexec` instead. Tools like these can be installed once and serve utility/purpose in many places besides just for uvu. :)

**Comment by aleclarson** [comment]
@lukeed Check it out: https://github.com/aleclarson/uvu-watch

**Comment by lukeed** [comment]
@aleclarson Cool :) You can link to this in the watch docs if you'd like. I still don't think it belongs in core `uvu` though.
