### ISSUE TITLE
Startup with Typescript is really slow.

### ISSUE THREAD

**Issue by dev-ardi** [lukeed/uvu#218]
## UVU

`$ time uvu -r tsm __tests__/`: 
uvu said:
>  Duration:  636.19ms

time said:
>real    0m2.218s
user    0m0.030s
sys     0m0.076s

## ESbuild

Compiling my source: `$ time esbuild src/init/pipeline.ts --bundle --minify --outfile=build/out.js --platform=node --sourcemap`:

ESbuild said

> Done in 46ms

time said:
> real    0m0.359s
> user    0m0.015s
> sys     0m0.060s

Where does the extra time go? How can I speed this up?

Well yes, it's only 2.2s, but I'd really like this to be as fast and snappy as it could. I don't think ESbuild and compiling here is the bottleneck. I haven't tried uvu either in javascript instead of typescript so I don't have a feel for how fast it should be but it feels wrong that it's this slow.

**Comment by AlexVipond** [comment]
```
npm i esbuild esbuild-register -D
npx uvu -r esbuild-register __tests__/
```

**Comment by lukeed** [comment]
The extra time goes into resolving and transpiling each file as it is requested. Node isn’t known for fast resolution, and it’s a file by file basis. esbuild bundling isn’t the same comparison since it’s all done in Go and, more importantly, in one pass rather than file by file. It’s not doing node -> resolve() -> transform -> run -> resolve() -> transform -> … like the uvu -r approach needs to do. 

uvu reports total test time, which begins after the require hooks (and requires themselves & therefore transpiles)
