### ISSUE TITLE
Feature proposal: teardown function

### ISSUE THREAD

**Issue by kim366** [lukeed/uvu#54]
One of the things I liked best in my days of C++ was RAII, i.e., automatic destruction of resources on scope exit. AVA has something that comes close to that, called `t.teardown` (https://github.com/avajs/ava/blob/master/docs/02-execution-context.md#tteardownfn). It allows to write utility functions that clearly show what resources are used in which test in the following way:

```js
function renderComponent(t, component) {
  const instance = new component();
  t.teardown(() => instance.destroy());
  return instance;
}

test('my test', t => {
  const component = renderComponent(t, myComponent)
});
```

This has the benefit over the `before.each` function that we only take resources that we actually need in this particular test.

I would be willing to implement this, I would just like to get the OK from maintainers.

**Comment by lukeed** [comment]
Hey,

There's already a stateful [suite context](https://github.com/lukeed/uvu/blob/master/docs/api.uvu.md#context-1) you can access for this. So you can couple that with the existing `after.each` (or `after`) [hook](https://github.com/lukeed/uvu/blob/master/docs/api.uvu.md#hooks) to implement your own teardown.

Your example c/would look like this:

```js
function render(context, component) {
  context.component = new component();
  return context.component;
}

test.after.each(context => {
  if (context.component) {
    context.component.destroy();
  }
});

// ---

test('my test', context => {
  const component = render(context, Component);
  // ...
});
```

Of course, the `after.each` bit can be extracted into a shared function for reuse.

Other people have taken to wrapping their suite(s) like this:

```js
function withRender(suite) {
  suite.before(ctx => {
    ctx.render = component => {
      ctx.component = new component();
      return ctx.component;
    };
  });

  suite.after.each(ctx => {
    if (ctx.component) {
      ctx.component.destroy();
    }
  });
}

// ---

const mysuite = suite('hello');
withRender(mysuite); // hooks added

mysuite('my test', ctx => {
  const component = ctx.render(Component);
  // ...
});
```

Closing this since I think this shows that uvu already has all the pieces to achieve what's desired here. If I'm missing something please let me know.

Hope that helps, thanks!
