### ISSUE TITLE
Generate snapshots?

### ISSUE THREAD

**Issue by darbymanning** [lukeed/uvu#65]
I couldn't tell from the docs if it's possible to generate a snapshot through the CLI? ie. something similar to [Jest's approach](https://jestjs.io/docs/en/snapshot-testing). Otherwise, I think manually getting the stringified output to compare against is "fine" but not the nicest DX, and it will make it hard to switch over to using uvu without that functionality.

Great work though with this tool!

**Comment by lukeed** [comment]
Hey,

So _not_ generating/auto-updating snapshots was an intentional decision here. I have seen teams get foiled by `jest -u` time and time again. It (almost) forces you to gloss over / hand wave any differences in snapshot results – **especially** when there's lots of them. More than one client has directly compared it to reviewing `package-lock`/`yarn.lock` diffs. 

I do not want to encourage – or make it easy for – devs to ignore such an important aspect of your application. 

And then, on a technical basis, generating snapshots wouldn't be (easily) possible to do in the browser. Everything else in `uvu` and `uvu/assert` is setup for Node _and_ browser compatibility. Bringing in `fs.writeFile` suddenly ruins that.

For when you really need to generate snapshot outputs, I do something like this:

```js
import * as fs from 'fs';
import { suite } from 'uvu';
import * as path from 'path';
import { promisify } from 'util';
import * as assert from 'uvu/assert';
import { transform } from '../module';

const read = promisify(fs.readFile);
const write = promisify(fs.writeFile);
const fixtures = path.join('path/to/fixtures');
// fixtures
//   |- test1/input.js
//   |- test1/expect.js
//   |- test2/input.js
//   |- test2/expect.js

const JSX = suite('JSX');

fs.readdirSync(fixtures).forEach(dir => {
  JSX(dir, async () => {
    let infile = path.join(fixtures, dir, 'input.js');
    let outfile = path.join(fixtures, dir, 'expect.js');

    let input = await read(infile, 'utf8');
    let result = await transform(input);

    // uncomment to save output
    // await write(outfile, result);

    assert.fixture(result.code, await read(outfile, 'utf8'));
  });
});

JSX.run();
```

Note that this generates output only when the `write` is uncommented. It's still a manual "ok, update everything" action. All other times, the test is just reading from an existing fixture for comparison.

Hopefully that helps – or at least helps explains things from my PoV!

**Comment by aleclarson** [comment]
FWIW, when I have a mismatched snapshot in Jest, I focus that test (with `fit`) so that `-u` (or `u` key in interactive mode) only updates the snapshots for that specific test.

**Comment by lukeed** [comment]
Consider yourself the exception then :) 

I am aware of this, but it _is far from_ the common case. Removing the temptation/risk of causing issues.

**Comment by aleclarson** [comment]
I just realized Jest has an "Interactive Snapshot Mode" that lets you update one snapshot at a time. Pretty nifty. Maybe the interactive mode could be the *only* way to update snapshots in Uvu. :o

**Comment by lukeed** [comment]
Please read the above. Snapshots, in the form familiar to Jest developers, will never come to uvu for the reasons listed above.

The closest thing `uvu/assert` will provide is `assert.snapshot` and `assert.fixture`, both of which are string comparisons and most similar to Jest's inline snapshot.

For anything else, please see the example snippet above. You may also find and use any third-party assertion library in conjunction with (or instead of) `uvu/assert`.

This is by design. I knew I was not going to include snapshots before the first line of uvu code was written.

**Comment by milahu** [comment]
> For when you really need to generate snapshot outputs, I do something like this:

another snippet

<details>

```js
// test/fixtures.test.js

import tsToJsdoc from '../index.js'
//import tsToJsdoc from 'ts-to-jsdoc'

// https://github.com/lukeed/uvu/blob/master/docs/api.assert.md
// https://github.com/lukeed/uvu/issues/65 # snapshot files

import * as fs from 'fs';
//import { test } from 'uvu';
import { suite } from 'uvu';
import * as path from 'path';
import { promisify } from 'util';
import * as assert from 'uvu/assert';

const read = promisify(fs.readFile);
const write = promisify(fs.writeFile);
const exists = promisify(fs.exists);
const fixtures = path.resolve(__dirname, './fixtures');
// fixture files
//   test/fixtures/test1/input.ts
//   test/fixtures/test1/expect.js
//   test/fixtures/test2/input.ts
//   test/fixtures/test2/expect.js

// use pattern to select test files -> ignore fixture files
//  "scripts": {
//    "test": "uvu -r esm test/ '\\.test\\.js$'"
//  },

const testSuite = suite('fixtures');

fs.readdirSync(fixtures).forEach(dir => {
  testSuite(dir, async () => {
    let infile = path.join(fixtures, dir, 'input.ts');
    let outfile = path.join(fixtures, dir, 'expect.js');
    //let actualfile = path.join(fixtures, dir, 'actual.js');

    let input = await read(infile, 'utf8');

    //let result = await transform(input);
    //let actual = result.code;
    let actual = tsToJsdoc(input, infile);

    console.log(`input:\n---\n${input}\n---\n\nactual:\n---\n${actual}\n---`) // debug

    if (await exists(outfile) == false || process.env['UPDATE_SNAPSHOTS']) {
      // save snapshot to file
      await write(outfile, actual);
      // no assert. we have no expect value here
    }
    else {
      let expect = await read(outfile, 'utf8')
      assert.fixture(actual, expect);
      // TODO else: write actual result to actualfile
    }
  });
});

testSuite.run();
```

</details>

**Comment by shellscape** [comment]
snapshots is still one of the things keeping me on ava. for as much as I've come not to like about it, they're really, really good.
