### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by AlexVipond** [lukeed/uvu#69]
In 0.5.0, there appears to be an issue with how the test queue gets set up, at least when using the `uvu -r esm` setup with modules.

Full console error:
```
TypeError: Cannot read property 'push' of undefined
    at Function.test.run (<pathToCWD>/node_modules/uvu/dist/index.js:107:36)
    at Object.<anonymous> (<pathToCWD>/tests/test.js:9:7)
    at Generator.next (<anonymous>)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
```

Reproduction:
https://github.com/AlexVipond/undefined-queue

Just clone the repo, `npm i`, and `uvu -r esm` to produce the error.

I'm on Node 15.1.0, and downgrading to uvu@0.4.1 fixes the problem

**Comment by lukeed** [comment]
Hey,

You have to add the `type: module`, shown [here](https://github.com/lukeed/uvu/tree/master/examples/esm.dual)

This is because on Node 15, you _do_ natively support ESM, but you're asking to pipe your test files thru the `esm` polyfill/loader. What happens is that the "setup" half (CLI + importer) of `uvu` is already in the ESM world, but your tests are loading the CommonJS half because of the `esm` rewrite(s).

Using `type: module` fixes this because it allows `esm` to be less aggressive in its approach. It recognizes that it may be in an environment where it can fallback to native behavior. In other words, on Node 15, everything is allowed to be the ESM halves, which means the same `QUEUE` is used throughout.

Hope that helps!

**Comment by marianmeres** [comment]
Hey @lukeed, I'm getting the same error on Node 14. Suggested `type: module` introduced different error `ReferenceError: require is not defined` (probably because of missing `esm`...). Downgrade to `^0.4.1` helps.

Thank you and thanks for your great work on other repos as well!
