### ISSUE TITLE
Don’t use Date to measure test duration

### ISSUE THREAD

**Issue by jasonwilliams** [lukeed/uvu#70]
it looks like you fallback to Date if you’re not in Node https://github.com/lukeed/uvu/blob/master/src/index.js#L5 

Date is subject to changes in “system time” and can potentially give you negative results, it’s not good to use for measuring. Instead use Performance.now(), it works in both Node and the browser. 
You haven’t expressed what browsers or versions of node you’re willing to support for this project so it’s hard for me to say if it will be ideal but you’re better off using that. It’s monotonic, designed for measuring duration and cross platform.

**Comment by lukeed** [comment]
Hey, yeah, should swap to [`performance.now`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now#Browser_compatibility) since it's well supported. Any puppeteer/playwright wrapper will be running an engine that supports this. In the off chance someone is running `uvu` in a browser that doesn't support `performance` global, they can either find-n-replace for `Date`, or we can add a `--legacy` flag that reverts to current `Date.now` approach.

In Node.js `performance` lives behind `perf_hooks`, and there's really no need to reach for it. The current [`process.hrtime`](https://nodejs.org/api/process.html#process_process_hrtime_time) is already high resolution.

**Comment by lukeed** [comment]
Actually, would be better to keep the `Date.now` upfront. And then `else if` to overwrite with the `performance` variant for browsers. This way it's non-breaking and there's no need to fuss with flags/unhappy users down the road.

```js
// current
let hrtime = (now = Date.now()) => () => (Date.now() - now).toFixed(2) + 'ms';

if (isNode = typeof ....) {
  // hrtime = ...
} else if (typeof performance < 'u') {
  hrtime = (now = performance.now()) => (performance.now() - now).toFixed(2) + 'ms';
}
```

**Comment by jasonwilliams** [comment]
> or we can add a --legacy flag that reverts to current Date.now approach

Honestly I think you’re safe to assume performance exists in the browser at this stage, no one is going to be running the test runner in an old version of IE. Especially as it’s a development tool and not something end-users will ever see. 

https://caniuse.com/high-resolution-time

**Comment by lukeed** [comment]
Definitely, but the thing is I already know people who are using uvu to run IE8-9 tests (bundled, mounted manually as script tag).

I think the else-if chain is the best of both. Practically everyone will be getting `peformance` and the "baggage" is one unused line

**Comment by vaelinn123** [comment]
Just wanted to add to the conversation here. When I run a test where I am using sinons useFakeTimers function the output of the Duration value is skewed by that:

![Screen Shot 2020-11-27 at 4 30 38 PM](https://user-images.githubusercontent.com/15093357/100490219-8f451e80-30ce-11eb-87e9-87e109061818.png)

The above is reproduced by having this block in a test.before.each block of a test:

```
useFakeTimers(new Date("11-10-2010"));
```

I can probably put together a test that reproduces this pretty easily if there is interest.

In any case, thanks for this package, just found it today and am really enjoying it 👍
