### ISSUE TITLE
Cannot find name VoidFunction

### ISSUE THREAD

**Issue by lo1tuma** [lukeed/uvu#89]
I’m trying to use `uvu` in a nodejs project, but I get a typescript error that `VoidFunction` is not defined.

```
node_modules/uvu/index.d.ts:16:10 - error TS2304: Cannot find name 'VoidFunction'.  
```

**Comment by zaboco** [comment]
It seems that the interface `VoidFunction` is [defined in `lib.dom.d.ts`](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.voidfunction.html). 

From what I saw, the "dom" lib is included by default if no `compilerOptions.lib` option is defined in `tsconfig.json`. But once that option is specified (e.g. `"lib": ["es2019"]`), "dom" needs to be explicitly added.

Or, another, more portable, option would be to use `() => void` instead of `VoidFunction` in `uvu/index.d.ts`.

**Comment by lukeed** [comment]
Hey, thanks for this. A few weeks ago I learned that `VoidFunction` _wasn't_ a global (like `Record`, `Pick`, etc) like I had thought. Will be part of the next release.
